### ISSUE TITLE
Eval4 Agents Training Data #2

### ISSUE THREAD

**Issue by bainro** [NextCenturyCorporation/mcs-scene-generator#16]
Hello,

I'm following the readme instructions to create the eval4 agents training data. I downloaded the NYU style json scenes and converted them using generate_public_scenes.py. It works but then the images returned from the MCS controller look like this:

![image](https://user-images.githubusercontent.com/31903812/118002860-e2b5cc80-b2fc-11eb-8618-707968fc5d5e.png)

machine_common_sense is v0.4.1
ai2thor is 2.5.0
the unity app is v0.4.1

**Comment by ThomasSchellenbergNextCentury** [comment]
Hi @bainro 

Yes, this was an issue with v0.4.1, but was fixed in v0.4.1.1 -- you can read more about it on [Confluence](https://nextcentury.atlassian.net/wiki/spaces/MCSC/pages/1953235098/Eval+4+Engineering+Information+and+Releases#0.4.1.1-Release-%E2%80%93-April-6-2021). Also note that we released v0.4.2 last week if you want to upgrade (more info on that Confluence page).

**Comment by bainro** [comment]
Awesome, thanks Thomas :) !

**Comment by ThomasSchellenbergNextCentury** [comment]
@bainro I also want to make sure you're aware that we've already generated all of the agent training scenes (converting the NYU scenes into MCS JSON format) and posted a ZIP of them on Confluence under [Training Information - Downloads - Passive Agent Training Datasets - Scene Files](https://nextcentury.atlassian.net/wiki/spaces/MCSC/pages/1953235098/Eval+4+Engineering+Information+and+Releases#Scene-Files). So you don't need to use our Scene Generator software to make these scenes, unless you want more variety in the shapes and colors that are used in the scenes! (The conversion process will choose pseudo-random shapes and colors for the agents and objects each time it's run.)

**Comment by bainro** [comment]
You're a legend. I was not aware!

**Comment by ThomasSchellenbergNextCentury** [comment]
Glad I could help! And sorry it didn't occur to me to mention it until now :)
