### ISSUE TITLE
Shortcut Option to Generate a Tool and a Target Encircled by Lava

### ISSUE THREAD

**Issue by ThomasSchellenbergNextCentury** [NextCenturyCorporation/mcs-scene-generator#74]
Blockers: https://github.com/NextCenturyCorporation/mcs-scene-generator/issues/36

Main requirement: We need to be able to generate scenes containing a block tool and a target (soccer ball) encircled by lava. Possible approaches may include:
1. Add a bool shortcut config option that automatically generates the block tool, target (soccer ball), and lava in the scene.
2. Add a bool config option (maybe a keyword location?) that automatically generates lava to encircle the target (or any interactable object?). The user would include the target and block tool in their YAML config file.

Additional requirements:
- The lava pool needs to be at least 2 units thick on each side.
- The thickness of the lava, as well as the size of the encircled island, should vary a little.
- There needs to be enough space to move around all sides of the lava (and also, ideally, the block tool).

Nice-to-haves:
- The target and block tool should be positioned orthogonally to each other. If we're implementing option 2 above, maybe we could add a second config option (or another keyword location) to configure the position of the block tool?

Make sure you branch off from the tool PR: https://github.com/NextCenturyCorporation/mcs-private/pull/123

![Screenshot from 2022-02-21 15-24-25](https://user-images.githubusercontent.com/10994382/155022054-158bcc75-8ecb-4586-8d01-fb2aa22ce2c9.png)
![Screenshot from 2022-02-21 15-24-06](https://user-images.githubusercontent.com/10994382/155022060-ac91b23b-d775-4783-bd1b-a57d1b92d252.png)

**Comment by ThomasSchellenbergNextCentury** [comment]
@kdrumm Forgot to include something: the total width (or length) of the entire area (both sides of the lava plus the island) should be no greater than 9 units, since our longest tool is currently 9 units (we may decide to increase this number in the future, but let's use 9 for now). So the following would be allowed:
- 3 units of lava, 3 units of island, 3 units of lava = 9 units
- 4 units of lava, 1 unit of island, 4 units of lava = 9 units
- 6 units of lava, 1 unit of island, 2 units of lava = 9 units

**Comment by kdrumm** [comment]
@ThomasSchellenbergNextCentury Just to confirm, the lava does not need to be uniform around the island?

**Comment by ThomasSchellenbergNextCentury** [comment]
@kdrumm Correct
